### PR TITLE
runtime/strings: add implementation of strings.IndexByte()

### LINKED ISSUE #154: strings.IndexByte not yet implemented
When trying to call `strings.Contains()` I get the following message:

```shell
/tmp/tinygo124212217/main.o: In function `strings.Index':
../../../../../../../gos/go1.11/src/strings/strings.go:995: undefined reference to `strings.IndexByte'
```

Does this mean that the `strings.IndexByte()` function is not yet implemented in TinyGo? If so, then where exactly should it be added?

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds implementation of `strings.IndexByte()` which resolves #154

### CODE REVIEW

**Comment by deadprogram** [comment]
The build failed on AVR with https://travis-ci.com/aykevl/tinygo/jobs/172959382#L1639

I'm not sure how to fix that...

**Comment by aykevl** [comment]
That's a compiler bug. I'll take a look...

**Comment by aykevl** [comment]
I pushed a fix: 85108514df5ccc80cffb6409503b1d10bdb05b4d.

**Comment by deadprogram** [comment]
Great, thanks! Good to merge?

**Comment by aykevl** [comment]
Yes this one looks great!
(By the way, this is one of the places where bounds check elimination would really help. But of course that's a performance issue and small code size issue that I want to take on at a later time.)

**Comment by deadprogram** [comment]
OK, merging.

**Pull request merged**
