### PR TITLE
Dockerfile, README, docs: Remove entrypoint

### PR DESCRIPTION
**Pull request by johanbrandhorst**
This was causing more trouble than it was helping, so lets remove it.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Not sure what CMD would give us in this case? Can you think of an example where it might be useful? It's been a while since I studied the difference between CMD and ENTRYPOINT closely.

**Comment by deadprogram** [comment]
`CMD` is basically a default command vs. `ENTRYPOINT` which is the only permitted command.

So by using `CMD` the default behavior with no other param would still be to display the usage info. But you can still specify a different command using `tinygo` like your examples or use a shell for development within the container.

**Comment by deadprogram** [comment]
Hi @johanbrandhorst any thoughts on my feedback?

**Comment by johanbrandhorst** [comment]
So we would set `CMD ["tinygo", "--help"]` you mean?

**Comment by deadprogram** [comment]
I think just `CMD ["tinygo"]` will work, since the default is to display usage.

**Comment by johanbrandhorst** [comment]
OK, I can do that

**Comment by johanbrandhorst** [comment]
@deadprogram This what you had in mind?

**Comment by deadprogram** [comment]
Yes, seems good. Thanks.

**Comment by aykevl** [comment]
Are the documentation changes still correct?

**Comment by johanbrandhorst** [comment]
Yes, the change only relates to running it without any parameters at all.

**Comment by aykevl** [comment]
Okay thank you, merged in a830451426f0ac60d2e70ccc0014d2801d761a44.

**Pull request closed without merging**
