### PR TITLE
Implement stm32f103xx SPI interface

### PR DESCRIPTION
**Pull request by deadprogram**
This PR implements the SPI interface for the STM32F103XX series of microcontrollers such as the "bluepill".

Before merging this PR, it requires that PR https://github.com/aykevl/tinygo/pull/111 be merged first.

### CODE REVIEW

**Comment by deadprogram** [comment]
Once the other PR has landed only commit https://github.com/aykevl/tinygo/pull/112/commits/bedc8a451758629a04b64c02397eda344ff4cc51 should be needed.

**Comment by aykevl** [comment]
Is UART still working with this PR?

**Comment by deadprogram** [comment]
Yes, just verified.

**Comment by aykevl** [comment]
Merged in dccfae485c9c5830e1ec012dfb9eb5af5fd10699.

**Pull request closed without merging**
