### PR TITLE
compiler: implement binop string: <, <=, >, >=

### PR DESCRIPTION
**Pull request by maruel**
add stringCmp(). Not fully tested if I haven't made an error.
Improve the test a bit to be more readable.

### CODE REVIEW

**Comment by aykevl** [comment]
I think it is relatively easy to extend this PR to also include `<` instead of just `>`, and to simplify/shrink the generated code:

 * Instead of implementing the equivalent of `strcmp` which returns 1, 0, or -1, it is simpler to implement a function `stringLess` (in line with `Sort.Less`) that simply returns a boolean. The code to check this should be smaller. It can be used directly to implement the `<` binop.
 * To implement this binop for `>`, simply swap the two parameters you give it.

**Comment by aykevl** [comment]
Oh and there are also the `>=` and `<=` binops. They can also be added with the same `stringLess` function: simply do the inverse operation and do a 'not' on the result. For example, `>=` is equal to to doing `<` and negating the result (see `CreateNot` in the [LLVM docs](https://godoc.org/github.com/llvm-mirror/llvm/bindings/go/llvm#Builder.CreateNot)).

**Comment by maruel** [comment]
Done

**Comment by deadprogram** [comment]
Looks good to me!

**Comment by aykevl** [comment]
Looks good to me as well! Will merge soon (tomorrow or Saturday probably).
Just one thing if you want to do that: there is no check on strings with the same prefix (like `a < "aa"`). It would be great if you could add such a test as well.

**Comment by maruel** [comment]
Done

**Comment by aykevl** [comment]
Thank you! Merged now.

**Pull request merged**
