### PR TITLE
Basic support for atsamd21g18 processor

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds support for the atsamd21g18 processor such as that used by the Adafruit ItsyBitsy M0 board. That is the only board with a target added by this PR. 

Only the GPIO and `time.Sleep()` interfaces are currently supported. Additional PR's will add other processor features.

In order to flash a board using the UF2 bootloader, you must first build the BIN file:

```
tinygo build -target=itsybitsy-m0 -size=short -o blinky1.bin examples/blinky1
```

Then you can use the UF2 utils converter/flasher from the https://github.com/Microsoft/uf2 repo to load the code on your board:

```
uf2/utils/uf2conv.py ./blinky1.bin
```

### CODE REVIEW

**Comment by deadprogram** [comment]
The docs claim that the bootloader is `bossa` compatible: https://learn.adafruit.com/adafruit-feather-m0-express-designed-for-circuit-python-circuitpython/uf2-bootloader-details

Indeed, I was able to flash the board without errors using `bossac` and the command in the json file.

However, on reboot, the board with UF2 just loads the UF2 bootloader again and not my user code. Not sure why that is as of yet.

**Comment by aykevl** [comment]
Wouldn't it be better to use `uf2conv.py` if `bossac` doesn't work well? It seems to support .hex files as well.

**Comment by deadprogram** [comment]
I was trying to avoid the "installation" of this into the user's Python env. is the part I was trying to avoid at least for the moment. It is a single, self-contained script, so that is also a possible option if you think that is better.

In the near future I expect to have a binary solution is the form of a Golang command line tool or something to handle this.

**Comment by aykevl** [comment]
... and it failed:

```
$ tinygo build -o blinky1.samd21.elf    -target=itsybitsy-m0     examples/blinky1
# device/sam
src/device/sam/atsamd21g18a.go:4546:2: SERCOM_USART_BAUD_BAUD_Pos redeclared in this block
src/device/sam/atsamd21g18a.go:4542:2: 	other declaration of SERCOM_USART_BAUD_BAUD_Pos
src/device/sam/atsamd21g18a.go:4547:2: SERCOM_USART_BAUD_BAUD_Msk redeclared in this block
src/device/sam/atsamd21g18a.go:4543:2: 	other declaration of SERCOM_USART_BAUD_BAUD_Msk
src/device/sam/atsamd21g18a.go:4552:2: SERCOM_USART_BAUD_BAUD_Pos redeclared in this block
src/device/sam/atsamd21g18a.go:4542:2: 	other declaration of SERCOM_USART_BAUD_BAUD_Pos
src/device/sam/atsamd21g18a.go:4553:2: SERCOM_USART_BAUD_BAUD_Msk redeclared in this block
src/device/sam/atsamd21g18a.go:4543:2: 	other declaration of SERCOM_USART_BAUD_BAUD_Msk
src/device/sam/atsamd21g18a.go:4554:2: SERCOM_USART_BAUD_FP_Pos redeclared in this block
src/device/sam/atsamd21g18a.go:4548:2: 	other declaration of SERCOM_USART_BAUD_FP_Pos
src/device/sam/atsamd21g18a.go:4555:2: SERCOM_USART_BAUD_FP_Msk redeclared in this block
src/device/sam/atsamd21g18a.go:4549:2: 	other declaration of SERCOM_USART_BAUD_FP_Msk
src/device/sam/atsamd21g18a.go:4558:2: SERCOM_USART_BAUD_BAUD_Pos redeclared in this block
src/device/sam/atsamd21g18a.go:4542:2: 	other declaration of SERCOM_USART_BAUD_BAUD_Pos
src/device/sam/atsamd21g18a.go:4559:2: SERCOM_USART_BAUD_BAUD_Msk redeclared in this block
src/device/sam/atsamd21g18a.go:4543:2: 	other declaration of SERCOM_USART_BAUD_BAUD_Msk
The command "tinygo build -o blinky1.samd21.elf    -target=itsybitsy-m0     examples/blinky1" exited with 1.
```

**Comment by deadprogram** [comment]
Need to update the submodule to the master branch of cmsis-svd with my PR that has the latest SVD files from Atmel. Should that be in a separate PR?

**Comment by aykevl** [comment]
You can add it to this PR or make a new one, what you prefer. I can make it a separate commit with some history rewriting to add it as the first commit, or merge them all. I just want the tests to pass for every commit.

**Comment by aykevl** [comment]
Merged in 1f511786d3a56c1c665ff013749f8665f7a1a663..e2be7ccf76ae9f8548394e715193e03ab47c18d6.

**Pull request closed without merging**
