### PR TITLE
Correct error generating device wrapper files from SVD files.

### PR DESCRIPTION
**Pull request by deadprogram**
Correct an error when generating device files from the SVD files that calculated the address incorrectly after a cluster type.

### CODE REVIEW

**Comment by deadprogram** [comment]
This PR appears to be working well for the NRF boards, and should be ready for merge.

**Comment by aykevl** [comment]
What I do for such changes is that I make sure existing known-working generated .go files are equivalent. I usually use the `meld` tool for that, but `diff` also works of course. In particular, fixing nrf52840 support should not change the .go files for nrf52832 and nrf51822, or fix the same bug there. Have you checked that?

Apart from that, the amount of spaghetti starts to get problematic but I can

**Comment by aykevl** [comment]
Oops wrong button

**Comment by deadprogram** [comment]
I did already do a file diff, and it does fix the same apparent bug by removing extra padding. But more importantly the change did not have any other visible side effects on other functionality. That is what I was pointing out.

**Comment by aykevl** [comment]
For nrf51 I see a single change in the PPI controller:

```diff
--- nrf.old/nrf51.go	2018-12-01 13:44:28.874332930 +0100
+++ nrf/nrf51.go	2018-12-01 13:44:33.270322721 +0100
@@ -717,20 +717,20 @@
 type PPI_Type struct {
 	TASKS_CHG [4]struct {
 		EN  RegValue
 		DIS RegValue
 	}
-	_padding0 [312]RegValue
+	_padding0 [318]RegValue
 	CHEN      RegValue
 	CHENSET   RegValue
 	CHENCLR   RegValue
 	_padding1 RegValue
 	CH        [16]struct {
 		EEP RegValue
 		TEP RegValue
 	}
-	_padding2 [156]RegValue
+	_padding2 [186]RegValue
 	CHG       [4]RegValue
 }
```

The old code was equivalent to the [C struct](https://github.com/NordicSemiconductor/nrfx/blob/v1.4.0/mdk/nrf51.h#L1077) while the new one isn't, so I think this PR introduces a bug here.

For nrf52, the patch appears to fix most issues. I haven't checked all of the changes but the ones I checked fixed incorrect padding.

**Comment by deadprogram** [comment]
Good catch. I  just pushed a change that corrects both the original offset error, along with another error that I discovered when there was a diff that turned out to be a different bug in the original script, by comparing the changes in the diff and then looking at the .h file.

Also this new update does not create additional offsets. 

Basically some subregisters are arrays, and some are just collections of registers. The subaddress calculation used for numSkip needs to take this into account.

**Comment by aykevl** [comment]
Merged in 70830cd9da2c74c5881af18b677a9d6fdfbadf71.

**Pull request closed without merging**
